version: "1"
services:
  - type: web
    name: scim-identity-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python create_sample_users.py && python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0